// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBrand: typeof import('./../src/components/BaseBrand/index.vue')['default']
    BaseLayout: typeof import('./../src/components/BaseLayout/index.vue')['default']
    BaseList: typeof import('./../src/components/BaseList/index.vue')['default']
    BaseListListItem: typeof import('./../src/components/BaseList/ListItem.vue')['default']
    BaseLoading: typeof import('./../src/components/BaseLoading.vue')['default']
    BasePanel: typeof import('./../src/components/BasePanel/index.vue')['default']
    DashBoardActiveMonitor: typeof import('./../src/components/DashBoard/ActiveMonitor/index.vue')['default']
    DashBoardEnergyMonitor: typeof import('./../src/components/DashBoard/EnergyMonitor/index.vue')['default']
    DashBoardEnvMonitor: typeof import('./../src/components/DashBoard/EnvMonitor/index.vue')['default']
    DashBoardErrorMonitor: typeof import('./../src/components/DashBoard/ErrorMonitor/index.vue')['default']
    DashBoardStatisticsMonitor: typeof import('./../src/components/DashBoard/StatisticsMonitor/index.vue')['default']
    DashBoardTurbineMonitor: typeof import('./../src/components/DashBoard/TurbineMonitor/index.vue')['default']
    DashBoardYawAngleMonitor: typeof import('./../src/components/DashBoard/YawAngleMonitor/index.vue')['default']
  }
}

export {}
