// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLogo: typeof import('./../src/components/BaseLogo.vue')['default']
    BaseMessageList: typeof import('./../src/components/BaseMessageList.vue')['default']
    BasePanel: typeof import('./../src/components/BasePanel.vue')['default']
    DashboardActive: typeof import('./../src/components/dashboardActive.vue')['default']
    DashboardEnergy: typeof import('./../src/components/DashboardEnergy.vue')['default']
    DashboardError: typeof import('./../src/components/DashboardError.vue')['default']
    DashboardTemperature: typeof import('./../src/components/DashboardTemperature.vue')['default']
    DashboardTotalParams: typeof import('./../src/components/DashboardTotalParams.vue')['default']
    DashboardTurbine: typeof import('./../src/components/DashboardTurbine.vue')['default']
    DashboardYawAngle: typeof import('./../src/components/DashboardYawAngle.vue')['default']
  }
}

export {}
